springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

spring:
  cloud:
    kubernetes:
      discovery:
        register: true

      config:
        enabled: true
        sources:
          - namespace: default
            name: mongo-db-config
      reload:
        enabled: true
        mode: polling
        period: 1000
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb://app_db:27017/wishlist


logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta([%t]) %m%n"

